### ISSUE TITLE
[Insight] Unused method, property, variable or parameter - in Model/Collection/GmailDomain.php, line 20

### ISSUE THREAD

**Issue by jonny-no1** [fourlabsldn/GmailBundle#4]
**[in Model/Collection/GmailDomain.php, line 20](https://github.com/fourlabsldn/GmailBundle/blob/e79a56fc53317eadb6d78366be8c541b83bf0ae1/Model/Collection/GmailDomain.php#L20)**

> This `domain` attribute is declared but never used. You should remove it.

```php
    private $gmailUsers;

    /**
     * @var string
     */
    private $domain;

    /**
     * LabelCollection constructor.
     *
     * @param string
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/2113fe3d-8256-4009-8d0c-8a84f21a7b59/analyses/1)_

**Comment by galeaspablo** [comment]
Fixed in 59267f37c3acf2f116e6b807402435b93d911d7e
